import logging

logging.basicConfig(level=logging.DEBUG)

GAME_NAME = 'TD2020'

FPS = 60
SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT = 1280, 650

CELL_SIZE = 50
FIELD_WIDTH = SCREEN_WIDTH // CELL_SIZE - 10
FIELD_HEIGHT = SCREEN_HEIGHT // CELL_SIZE - 2

RIGHT_BLOCK_CENTERX_POSITION = (FIELD_WIDTH * CELL_SIZE + SCREEN_WIDTH) // 2