import logging

logging.basicConfig(level=logging.DEBUG)

GAME_NAME = 'TD2020'

FPS = 60
SCREEN_SIZE = SCREEN_WIDTH, SCREEN_HEIGHT = 1100, 600

CELL_SIZE = 50
FIELD_WIDTH = SCREEN_WIDTH // CELL_SIZE - 6
FIELD_HEIGHT = SCREEN_HEIGHT // CELL_SIZE - 2